<?php
ob_start();
require_once '../auth.php'; // Assuming we create auth.php in admin folder

// Check if user has admin-like access
$isAdmin = isElevatedRole((string)($_COOKIE['auth_role'] ?? ''));
?>
<?php
// Admin UI to select active WhatsApp number for whatsapp_leads.php

$configPhp = __DIR__ . '/whatsapp_leads_config.php';
$configTxt = __DIR__ . '/whatsapp_leads_config.txt';

$numbers = [];
$current = null;
$message = null;
$labels = [];

function sanitize_number($n) {
    if ($n === 'AUTO') return 'AUTO';
    return preg_replace('/\D+/', '', (string)$n);
}

function get_label($n, $labels) {
    $n = sanitize_number($n);
    if (isset($labels[$n]) && $labels[$n] !== '') {
        return $labels[$n];
    }
    return null; 
}

// Load numbers and current from config 
if (file_exists($configPhp)) {
    include $configPhp; // expects $whatsappNumberList and $whatsappNumber
    if (isset($whatsappNumberList) && is_array($whatsappNumberList)) {
        $numbers = array_values(array_unique(array_map('sanitize_number', $whatsappNumberList)));
    }
    if (isset($whatsappNumber)) {
        $current = sanitize_number($whatsappNumber);
    }
    if (isset($whatsappNumberLabels) && is_array($whatsappNumberLabels)) {
        // Normalize labels keys to digit-only numbers
        foreach ($whatsappNumberLabels as $k => $v) {
            $labels[sanitize_number($k)] = trim((string)$v);
        }
    }
} elseif (file_exists($configTxt)) {
    $lines = file($configTxt, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    $lines = array_map('trim', $lines);
    $lines = array_filter($lines, function ($l) { return $l !== ''; });
    if (!empty($lines)) {
        $current = sanitize_number($lines[0]);
        $numbers = array_values(array_unique(array_map('sanitize_number', $lines)));
    }
}

// Handle selection update
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $selected = isset($_POST['number']) ? sanitize_number($_POST['number']) : '';
    if ($selected === '') {
        $message = 'Please select a number.';
    } else {
        if (file_exists($configPhp)) {
            $content = file_get_contents($configPhp);
            $updated = preg_replace('/\$whatsappNumber\s*=\s*["\']([^"\']*)["\'];/', '$whatsappNumber = "' . $selected . '";', $content, -1, $count);
            if ($count === 0) {
                $updated .= PHP_EOL . '$whatsappNumber = "' . $selected . '";' . PHP_EOL;
            }
            file_put_contents($configPhp, $updated);
            $current = $selected;
            // Refresh numbers from PHP config to maintain consistency
            include $configPhp;
            if (isset($whatsappNumberList) && is_array($whatsappNumberList)) {
                $numbers = array_values(array_unique(array_map('sanitize_number', $whatsappNumberList)));
            }
            $message = 'Active WhatsApp number updated.';
        } elseif (file_exists($configTxt)) {
            // Ensure selected is included and becomes the first line
            if (!in_array($selected, $numbers, true)) {
                $numbers[] = $selected;
            }
            $linesOut = array_merge([$selected], array_values(array_filter($numbers, fn($n) => $n !== $selected)));
            file_put_contents($configTxt, implode(PHP_EOL, $linesOut) . PHP_EOL);
            $current = $selected;
            $message = 'Active WhatsApp number updated.';
        } else {
            // No config exists; create PHP config by default
            $phpContent = "<?php\n// Auto-generated by whatsapp_leads_admin.php\n$whatsappNumberList = [\n    \"$selected\"\n];\n$whatsappNumber = \"$selected\";\n";
            file_put_contents($configPhp, $phpContent);
            $numbers = [$selected];
            $current = $selected;
            $message = 'Config file created and active number set.';
        }
    }
}

$schedule = [];
if (isset($whatsappSchedule) && is_array($whatsappSchedule)) {
    $schedule = $whatsappSchedule;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SM WhatsApp | Leads Admin</title>
  <link rel="icon" type="image/png" sizes="32x32" href="/content/uploads/2025/01/cropped-Site-Icon-32x32.png">
  <link rel="apple-touch-icon" href="/content/uploads/2025/01/cropped-Site-Icon-180x180.png">
    <style>
        body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 2rem; color: #222; }
        h1 { font-size: 1.5rem; margin-bottom: 1rem; }
        .card { border: 1px solid #ddd; border-radius: 8px; padding: 1rem; max-width: 520px; }
        .row { margin: 0.5rem 0; }
        .numbers { display: grid; grid-template-columns: 1fr; gap: 0.35rem; }
        .current { font-weight: 600; margin-bottom: 0.5rem; }
        .actions { margin-top: 1rem; }
        button { background: #0a7cff; color: #fff; border: none; border-radius: 6px; padding: 0.5rem 0.9rem; cursor: pointer; }
        button:hover { background: #075ec4; }
        .msg { margin-top: 0.75rem; padding: 0.5rem; border-radius: 6px; background: #f0f7ff; border: 1px solid #c9e4ff; }
        .hint { font-size: 0.9rem; color: #555; }
        .schedule-details { margin-top: 0.75rem; }
        .schedule-details > summary { cursor: pointer; user-select: none; font-weight: 600; }
        .schedule-table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; font-size: 0.9rem; }
        .schedule-table th, .schedule-table td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; }
        .schedule-table th { background: #f9fafb; font-weight: 700; }
        .schedule-table td code { font-size: 0.85rem; }
    </style>
</head>
<body>
    <h1>WhatsApp Leads Admin</h1>
    <div class="card">
        <div class="row current">
            Current active number: 
            <?php 
            if ($current === 'AUTO') {
                echo '<strong style="color: #673ab7;">Automatic (Follow Schedule)</strong>';
                // Show who is active right now
                if (file_exists($configPhp)) {
                    include $configPhp;
                    $today = date('D'); 
                    $autoNum = isset($whatsappSchedule[$today]) ? $whatsappSchedule[$today] : '';
                    $autoName = get_label($autoNum, $labels) ?: $autoNum;
                    echo " <span class='hint'>— right now it's <strong>$autoName</strong> ($today)</span>";
                }
            } else {
                echo htmlspecialchars($current);
                $lbl = get_label($current, $labels);
                if ($lbl) echo " ($lbl)";
            }
            ?>
        </div>
        <form method="post">
            <div class="row">
                <div class="hint">Select active mode:</div>
                <div class="numbers">
                    <!-- Auto Option -->
                    <label class="auto-option" style="background: #f3e5f5; border: 1px solid #d1c4e9; padding: 8px; border-radius: 4px; margin-bottom: 8px; display: block;">
                        <input type="radio" name="number" value="AUTO" <?php echo ($current === 'AUTO') ? 'checked' : ''; ?> />
                        <strong style="color: #673ab7;">Automatic Mode</strong>
                        <div class="hint" style="margin-left: 24px;">Automatically switches based on day of week (Amreen: Mon-Wed, Sophy: Fri-Sat)</div>
                    </label>

                    <?php if (!empty($numbers)) : ?>
                        <?php foreach ($numbers as $n): ?>
                            <?php if ($n === 'AUTO') continue; ?>
                            <?php $lbl = get_label($n, $labels); ?>
                            <label>
                                <input type="radio" name="number" value="<?php echo htmlspecialchars($n); ?>" <?php echo ($current === $n) ? 'checked' : ''; ?> />
                                <?php if ($lbl): ?>
                                    <strong><?php echo htmlspecialchars($lbl); ?></strong>
                                    <span class="hint">(<?php echo htmlspecialchars($n); ?>)</span>
                                <?php else: ?>
                                    <?php echo htmlspecialchars($n); ?>
                                <?php endif; ?>
                            </label>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="hint">No numbers configured yet. Submitting will create a config with your selection.</div>
                        <label>
                            <input type="radio" name="number" value="919886735991" checked />
                            919886735991
                        </label>
                    <?php endif; ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit">Update Active Number</button>
            </div>
            <details class="schedule-details">
                <summary>Schedule</summary>
                <div class="hint" style="margin-top: 0.35rem;">Used when Automatic Mode is selected.</div>
                <table class="schedule-table" aria-label="WhatsApp schedule">
                    <thead>
                        <tr>
                            <th>Day</th>
                            <th>Active</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
                        foreach ($days as $d) {
                            $num = isset($schedule[$d]) ? sanitize_number($schedule[$d]) : '';
                            $label = $num !== '' ? (get_label($num, $labels) ?: $num) : '-';
                            echo '<tr>';
                            echo '<td>' . htmlspecialchars($d) . '</td>';
                            echo '<td>' . htmlspecialchars($label) . ($num !== '' && get_label($num, $labels) ? ' <span class="hint">(' . htmlspecialchars($num) . ')</span>' : '') . '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
            </details>
        </form>
        <?php if ($message): ?>
            <div class="msg"><?php echo htmlspecialchars($message); ?></div>
        <?php endif; ?>
        <div class="row hint" style="margin-top: 0.75rem;">
            Source: prefers <code>whatsapp_leads_config.php</code> if present, otherwise <code>whatsapp_leads_config.txt</code>.
        </div>
    </div>
</body>
</html>
